/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>
#include "itm_send_data.h"

#define SHCSR_ADDR	0xE000ED24U	//system handler control and status register
#define MMSR_ADDR	0xE000ED28U	//MemManage Fault status register
#define BFSR_ADDR	0xE000ED29U	//BusFault status register
#define UFSR_ADDR	0xE000ED2AU	//UsageFault status register
#define HFSR_ADDR	0xE000ED2CU	//HardFault status register
#define MMAR_ADDR	0xE000ED34U	//MemManage Fault address register
#define BFAR_ADDR	0xE000ED38U	//BusFault address register

void delay(void){
	for(uint32_t i=0; i<500000; i++);
}

void HardFault_Handler(void){
	uint32_t* pHFSR = (uint32_t*)HFSR_ADDR;
	uint32_t status = *pHFSR & 0xC0000003;
	printf("HardFault_Handler status %lx\n", status);
	while(1);
}

void MemManage_Handler(void){
	uint8_t* pMMSR = (uint8_t*)MMSR_ADDR;
	uint32_t* pMMAR = (uint32_t*)MMAR_ADDR;
	uint8_t status = *pMMSR;
	uint32_t address = *pMMAR;
	printf("MemManage_Handler status %x\n", status);
	printf("MemManage Fault at address %lx\n", address);
	while(1);
}

void BusFault_Handler(void){
	uint8_t* pBFSR = (uint8_t*)BFSR_ADDR;
	uint32_t* pBFAR = (uint32_t*)BFAR_ADDR;
	uint8_t status = *pBFSR;
	uint32_t address = *pBFAR;
	printf("BusFault_Handler status %x\n", status);
	printf("BusFault Fault at address %lx\n", address);
	while(1);
}

void UsageFault_Handler(void){
	uint16_t* pUFSR = (uint16_t*)UFSR_ADDR;
	uint16_t status = *pUFSR & 0x030F;
	printf("UsageFault_Handler status %x\n", status);
	while(1);
}

int main(void){

	//enable usageFault, busFault, MemoryManage in SCB
	uint32_t *pSHCSR = (uint32_t*) SHCSR_ADDR;
	*pSHCSR |= (0b111 << 16);

	//declare any type of fault here
	//example: execution from wrong pc address
	void (*func_call)(void);
	func_call = (void*)0x20002001;		//T bit thumb state odd address
	func_call();

    /* Loop forever */
	while(1){
	}
}
